# Generated by Django 5.1.6 on 2025-03-07 13:00

import apps.candidate.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='RG')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Has disability')),
                ('disability_description', models.TextField(blank=True, null=True, verbose_name='Disability description')),
                ('has_drivers_license', models.BooleanField(default=False, verbose_name="Has driver's license")),
                ('is_first_job', models.BooleanField(default=False, verbose_name='Is first job')),
                ('is_currently_employed', models.BooleanField(default=False, verbose_name='Is currently employed')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=apps.candidate.models.Candidate.profile_picture_upload_to, verbose_name='Profile picture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidate_candidate',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'candidate_city',
            },
        ),
        migrations.CreateModel(
            name='DriversLicenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Categoria de CNH',
                'verbose_name_plural': 'Categorias de CNH',
                'db_table': 'candidate_drivers_license_category',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'db_table': 'candidate_gender',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Nome da rede social',
                'verbose_name_plural': 'Nomes das redes sociais',
                'db_table': 'candidate_social_network',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'candidate_state',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complement')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Neighborhood')),
                ('zip_code', models.CharField(max_length=8, verbose_name='ZIP code')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='candidate.candidate', verbose_name='Candidate')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'candidate_address',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='candidate.candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Informação de contato',
                'verbose_name_plural': 'Informações de contato',
                'db_table': 'candidate_contact',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='drivers_license_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='candidate.driverslicensecategory', verbose_name="Driver's license category"),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.gender', verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='SocialNetworkProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_network_profile', to='candidate.candidate', verbose_name='Candidate')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.socialnetwork', verbose_name='Social network')),
            ],
            options={
                'verbose_name': 'Perfil de rede social',
                'verbose_name_plural': 'Perfis de redes sociais',
                'db_table': 'candidate_social_network_profile',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.state', verbose_name='State'),
        ),
    ]
